### PR TITLE
feat: add api endpoint to support sendCall

### PR DESCRIPTION
**Pull request by comawill**
This PR adds the ability to initiate calls using the ets api

### CODE REVIEW

**Comment by atomrc** [comment]
@comawill can you provide a bit more context to why this is needed? I believe QA doesn't use the ETS at all for calling (they have a calling service I believe)

**Comment by comawill** [comment]
@atomrc I used this to have an easy method to send custom calling signalling data.
e.g. this resulted in a bug report here: https://wearezeta.atlassian.net/browse/SQCALL-573

**Comment by comawill** [comment]
So the main purpose from my side is more for experimenting with it, not for direct automation

**Review by atomrc — APPROVED** [review]

**Comment by atomrc** [comment]
Then LGTM :)

**Pull request merged**
